# .travis.yml for ices-tools packages

os:
  - linux

language: r
r:
  - oldrel
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  flr: http://flr-project.org/R

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
