# .travis.yml for ices-tools packages
#

warnings_are_errors: false

os:
  - linux
  - osx
  - windows

language: r

r:
  - release
  - devel

sudo: false

repos:
  CRAN: https://cloud.r-project.org
  flr: http://flr-project.org/R

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
