# .travis.yml for ices-tools packages

warnings_are_errors: false

os:
  - linux

language: r
r:
  - oldrel
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  flr: http://flr-project.org/R

r_packages:
  - rmarkdown

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
